### PR TITLE
Fix/867/remove required nasa

### LINKED ISSUE #867: [FEAT] - NASA API key should be optional, but is required
### What bug did you encounter?

Running the bot without the NASA api key is not possible, due to:
https://github.com/BeccaLyria/discord-bot/blob/main/src/modules/validateEnv.ts#L32-L34

even though the docs, and the `sample.env` say its optional.

### What did you expect to happen?

The bot should just print out a warning, or do nothing and let me run the bot.

### Screenshots

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by bradtaniguchi**
# Pull Request

## Description
- made the  `NASA_API` environment variable to be optional, will log a warning instead of erroring out.
- Updated `space` command to throw an error if `nasaKey`/`NASA_API` variables are not set correctly.

## Related Issue

Closes #867 

## Documentation

For _any_ version updates, please verify if the [documentation page](https://www.beccalyria.com/discord-documentation) needs an update. If it does, please [create an issue there](https://github.com/BeccaLyria/discord-documentation/issues/new?assignees=nhcarrigan&labels=%F0%9F%9A%A6+status%3A+awaiting+triage&template=update.md&title=%5BUPDATE%5D) to ensure it is not forgotten.

- [X] My contribution does NOT require a documentation update.
- [ ] My contribution DOES require a documentation update.

(this PR updates the code to match the docs)

### CODE REVIEW

File: src/modules/commands/subcommands/misc/handleSpace.ts [hunk 1]
```diff
@@ -5,6 +5,7 @@ import { MessageEmbed } from "discord.js";
 import { CommandHandler } from "../../../../interfaces/commands/CommandHandler";
 import { SpaceInt } from "../../../../interfaces/commands/general/SpaceInt";
 import { beccaErrorHandler } from "../../../../utils/beccaErrorHandler";
+import { beccaLogHandler } from "../../../../utils/beccaLogHandler";
```
Comment (nhcarrigan) [inline src/modules/commands/subcommands/misc/handleSpace.ts:8]: Extraneous import from https://github.com/BeccaLyria/discord-bot/pull/868/commits/d37953b6645410615f04340f5f10408a2e009926?

**Review by nhcarrigan — CHANGES_REQUESTED** [review]

**Review by nhcarrigan — APPROVED** [review]
Looks good to me!

**Comment by nhcarrigan** [comment]
## Congratulations

Congratulations on making your first pull request to our project. We have reviewed your contributions and are happy to accept them.

We hope you enjoyed the contribution process, and encourage you to watch for issues labelled `help wanted` for additional opportunities to contribute.
