### PR TITLE
fix: block more domains (#732)

### LINKED ISSUE #732: [BUG] - dev links are not blogged
### What bug did you encounter?

`*.dev` links are not blocked by the bot

### What did you expect to happen?

Link to be removed

### Additional information

I see there are 2 solutions

- add `dev` to the block list
- do not allow 3 characters after the `.`, currently it is set to 2 in the regex

### PR DESCRIPTION
**Pull request by eddiejaoude**
# Pull Request

## Description

Blocks more domains with `.*{3}`, for example `.dev`

## Related Issue

closes #732 

## Scope

Did you remember to update the `package.json` version number?

- [ ] Major Version Update: X.\_.\_ (for complete code refactors, or large PRs that adjust most of the codebase)
- [ ] Minor Version Update: \_.X.\_ (for the addition of new commands)
- [x] Patch Version Update: \_.\_.X (for bug fixes _in the code_.)
- [ ] No Version Update: \_.\_.\_ (no version update for additions to tests, documentation, or anything that isn't end-user facing.)

GitHub Action could automate this

## Documentation

For _any_ version updates, please verify if the [documentation page](https://www.beccalyria.com/discord-documentation) needs an update. If it does, please [create an issue there](https://github.com/BeccaLyria/discord-documentation/issues/new?assignees=nhcarrigan&labels=%F0%9F%9A%A6+status%3A+awaiting+triage&template=update.md&title=%5BUPDATE%5D) to ensure it is not forgotten.

- [x] My contribution does NOT require a documentation update.
- [ ] My contribution DOES require a documentation update.

### CODE REVIEW

File: src/listeners/linksListener.ts [hunk 1]
```diff
@@ -42,7 +42,7 @@ export const linksListener: ListenerInt = {
 
       // Borrowed from https://gist.github.com/arbales/1654670
       const linkRegex =
-        /(([a-z]+:\/\/)?(([a-z0-9-]+\.)+([a-z]{2}|aero|arpa|biz|com|coop|edu|gov|info|int|jobs|mil|museum|name|nato|net|org|pro|travel|local|internal))(:[0-9]{1,5})?(\/[a-z0-9_\-.~]+)*(\/([a-z0-9_\-.]*)(\?[a-z0-9+_\-.%=&amp;]*)?)?(#[a-zA-Z0-9!$&'()*+.=-_~:@/?]*)?)(\s+|$)/gi;
+        /(([a-z]+:\/\/)?(([a-z0-9-]+\.)+([a-z]{2,3}|aero|arpa|biz|com|coop|edu|gov|info|int|jobs|mil|museum|name|nato|net|org|pro|travel|local|internal))(:[0-9]{1,5})?(\/[a-z0-9_\-.~]+)*(\/([a-z0-9_\-.]*)(\?[a-z0-9+_\-.%=&amp;]*)?)?(#[a-zA-Z0-9!$&'()*+.=-_~:@/?]*)?)(\s+|$)/gi;
```
Comment (nhcarrigan) [inline src/listeners/linksListener.ts:45]:
```suggestion
        /(([a-z]+:\/\/)?(([a-z0-9-]+\.)+([a-z]{2,3}|aero|arpa|coop|info|int|jobs|museum|name|nato|travel|local|internal))(:[0-9]{1,5})?(\/[a-z0-9_\-.~]+)*(\/([a-z0-9_\-.]*)(\?[a-z0-9+_\-.%=&amp;]*)?)?(#[a-zA-Z0-9!$&'()*+.=-_~:@/?]*)?)(\s+|$)/gi;
```
Since we're catching 3 characters now, we can remove the explicit three-character TLDs. 🙂

**Review by nhcarrigan — CHANGES_REQUESTED** [review]
Thanks for taking care of this!

One quick change to DRY the regex a bit.

File: src/listeners/linksListener.ts (hunk 1 above)
Comment (eddiejaoude) [reply src/listeners/linksListener.ts:45]: oh yes good point 👍

**Review by nhcarrigan — APPROVED** [review]
Looks good to me!

**Comment by nhcarrigan** [comment]
## Congratulations

Congratulations on making your first pull request to our project. We have reviewed your contributions and are happy to accept them.

We hope you enjoyed the contribution process, and encourage you to watch for issues labelled `help wanted` for additional opportunities to contribute.
